### ISSUE TITLE
Can you include Bengali.AI competition? 

### ISSUE THREAD

**Issue by urvishp80** [faridrashidi/kaggle-solutions#1]
Hi, this is wonderful to see that you are hosting a site for wonderful solutions for Kaggle competition. Around two months back there was a competition named `Bengali.AI handwritten grapheme classification`. [Here](https://www.kaggle.com/c/bengaliai-cv19/overview) you can see the overview. It would be great to see it here as well.

**Comment by faridrashidi** [comment]
Hi @urvishp80, sure. I will give an update by the end of this week to add the recent two-month competitions.

**Comment by urvishp80** [comment]
Closing the issue then. I do not think it is needed now as you are planning to add them. Thanks for your quick response.
