### ISSUE TITLE
123. UPenn and Mayo Clinics Seizure Detection Challenge 1st place link

### ISSUE THREAD

**Issue by agamemnonc** [faridrashidi/kaggle-solutions#3]
Hi there, and thanks for this amazing repo!

I just noticed that the link to 1st place solution for competition "123. UPenn and Mayo Clinics Seizure Detection Challenge" points to a [Discussion](https://www.kaggle.com/c/seizure-detection/discussion/10092) concerning submission ranked 27th.

I believe the correct link should be this one here:
https://github.com/MichaelHills/seizure-detection

Happy to open a PR to fix this

**Comment by faridrashidi** [comment]
Thanks a lot for pointing to this issue. I fixed it here 5c66dc6bbbd2a2c0d6a468f7f2c861f7b3a9e727
