### ISSUE TITLE
can you add github /code link in website?

### ISSUE THREAD

**Issue by akashAD98** [faridrashidi/kaggle-solutions#5]
it would be great if you add GitHub link of a particular solution .like this guy has done https://github.com/tyamaguchi17/kaggle-happywhale-1st-place-solution-charmq.
also if you create one filter in the web app. it would be easy to do search. computer vision,NLP,ML competation

**Comment by faridrashidi** [comment]
Hi @akashAD98 ,
This solution has already been mentioned in the description of the winner (https://www.kaggle.com/c/happy-whale-and-dolphin/discussion/320192) but I generally tried to add separately the GitHub repos which haven't been mentioned in a winner description post.
It's a good idea, do you know where Kaggle provides these informations?

**Comment by akashAD98** [comment]
@faridrashidi I don't know all kagglers & solution winners are publishing their work on GitHub/code as open-source, but in if anyone mentioned their Github link on their winner's solution we need to check it manually & add it here. 
can i do this contribution?

**Comment by faridrashidi** [comment]
@akashAD98 If the code is already mentioned in the description by the winners then I think it's going to be redundant to add them separately and make the list longer. However, if you find any repo that is not mentioned in the description by winners please go ahead and add them, I'll accept your PR.
Just for your information, I read the winners' description before adding them to the list. Some are provided with the code and some are not. So, I distinguish them via a symbol (see https://farid.one/kaggle-solutions/resources/symbols.html)

**Comment by akashAD98** [comment]
@faridrashidi thanks for your info.
